Indoor get
WildCodeSchool/p3-g2-sept21-lille-eQay-backend pull request #5
Opened 2021-12-21 09:47 UTC by PierreGoe

2021-12-21 10:56 UTC, Mariion-62 approved these changes
it's okay

2021-12-22 08:37 UTC, Hacene010 requested changes
remove the console log plz

2021-12-22 08:37 UTC, Hacene010 commented on index.js
> +            `SELECT * FROM mesures WHERE adresses_longitude=? AND adresses_latitude=? ORDER BY timestamp LIMIT 1;`,
be aware about the select *

2021-12-22 08:37 UTC, Hacene010 commented on index.js
> +            console.log(result.length);
no console log !!!

2021-12-22 09:51 UTC, Hacene010 approved these changes

2021-12-22 13:03 UTC, merged